from myTrans.base_params import *

VOCAB_SIZE=95
token2idx = {
    # remain
    '<CLS>':CLS_ID, '<PAD>':PAD_ID,'<BOS>':BOS_ID, '<EOS>':EOS_ID,'<SEP>':SEP_ID,
    '<MASK>':MASK_ID,'<UNK>':UNK_ID, '<REM1>':REM_ID_1,'<REM2>':REM_ID_2, '<REM3>':REM_ID_3,
    # customize
    '清': 10, '他': 11, '包': 12, '果': 13, '买': 14, '谱': 15, '牛': 16, '我': 17, '踢': 18, '剧': 19, '赛': 20,
    '们': 21, '播': 22, '喜': 23, '水': 24, '她': 25, '乐': 26, '需': 27, '看': 28, '玩': 29, '吃': 30, '球': 31,
    '整': 32, '窗': 33, '件': 34, '洗': 35, '欢': 36, '读': 37, '擦': 38, '苹': 39, '比': 40, '奶': 41, '电': 42,
    '本': 43, '影': 44, '户': 45, '理': 46, '写': 47, '信': 48, '音': 49, '要': 50, '具': 51, '足': 52, '你': 53,
    '听': 54, '喝': 55, '放': 56, '书': 57, '面': 58, 'he': 59, 'they': 60, 'milk': 61, 'read': 62, 'movies': 63,
    'eats': 64, 'writes': 65, 'watch': 66, 'I': 67, 'needs': 68, 'buy': 69, 'she': 70, 'clean': 71, 'buys': 72,
    'reads': 73, 'plays': 74, 'music': 75, 'watches': 76, 'letters': 77, 'drinks': 78, 'toys': 79, 'bread': 80,
    'likes': 81, 'need': 82, 'football': 83, 'you': 84, 'apples': 85, 'write': 86, 'books': 87, 'cleans': 88,
    'windows': 89, 'play': 90, 'eat': 91, 'drink': 92, 'like': 93, 'water': 94}

idx2token = {v: k for k, v in token2idx.items()}

demo_data_train=[
    ("I eat apples", "我吃苹果"),
    ("I drink water", "我喝水"),
    ("I play football", "我踢足球"),
    ("I read books", "我看书"),
    ("I write letters", "我写信"),
    ("I watch movies", "我看电影"),
    ("I like music", "我喜欢音乐"),
    ("I need bread", "我需要面包"),
    ("I buy toys", "我买玩具"),
    ("I clean windows", "我擦窗户"),
    ("you eat apples", "你吃苹果"),
    ("you drink water", "你喝水"),
    ("you play football", "你踢足球"),
    ("you read books", "你看书"),
    ("you write letters", "你写信"),
    ("you watch movies", "你看电影"),
    ("you like music", "你喜欢音乐"),
    ("you need bread", "你需要面包"),
    ("you buy toys", "你买玩具"),
    ("you clean windows", "你擦窗户"),
    ("he eats apples", "他吃苹果"),
    ("he drinks water", "他喝水"),
    ("he plays football", "他踢足球"),
    ("he reads books", "他看书"),
    ("he writes letters", "他写信"),
    ("he watches movies", "他看电影"),
    ("he likes music", "他喜欢音乐"),
    ("he needs bread", "他需要面包"),
    ("he buys toys", "他买玩具"),
    ("he cleans windows", "他擦窗户"),
    ("she eats apples", "她吃苹果"),
    ("she drinks water", "她喝水"),
    ("she plays football", "她踢足球"),
    ("she reads books", "她看书"),
    ("she writes letters", "她写信"),
    ("she watches movies", "她看电影"),
    ("she likes music", "她喜欢音乐"),
    ("she needs bread", "她需要面包"),
    ("she buys toys", "她买玩具"),
    ("she cleans windows", "她擦窗户"),
    ("they eat apples", "他们吃苹果"),
    ("they drink water", "他们喝水"),
    ("they play football", "他们踢足球"),
    ("they read books", "他们看书"),
    ("they write letters", "他们写信"),
    ("they watch movies", "他们看电影"),
    ("they like music", "他们喜欢音乐"),
    ("they need bread", "他们需要面包"),
    ("they buy toys", "他们买玩具"),
    ("they clean windows", "他们擦窗户"),
    ("I eat bread", "我吃面包"),
    ("I drink milk", "我喝牛奶"),
    ("I play toys", "我玩玩具"),
    ("I read letters", "我读信"),
    ("I write books", "我写书"),
    ("I watch football", "我看足球赛"),
    ("I like apples", "我喜欢苹果"),
    ("I need water", "我需要水"),
    ("I buy books", "我买书"),
    ("I clean toys", "我清理玩具"),
    ("you eat bread", "你吃面包"),
    ("you drink milk", "你喝牛奶"),
    ("you play toys", "你玩玩具"),
    ("you read letters", "你读信"),
    ("you write books", "你写书"),
    ("you watch football", "你看足球赛"),
    ("you like apples", "你喜欢苹果"),
    ("you need water", "你需要水"),
    ("you buy books", "你买书"),
    ("you clean toys", "你清理玩具"),
    ("he eats bread", "他吃面包"),
    ("he drinks milk", "他喝牛奶"),
    ("he plays toys", "他玩玩具"),
    ("he reads letters", "他读信"),
    ("he writes books", "他写书"),
    ("he watches football", "他看足球赛"),
    ("he likes apples", "他喜欢苹果"),
    ("he needs water", "他需要水"),
    ("he buys books", "他买书"),
    ("he cleans toys", "他清理玩具"),
    ("she eats bread", "她吃面包"),
    ("she drinks milk", "她喝牛奶"),
    ("she plays toys", "她玩玩具"),
    ("she reads letters", "她读信"),
    ("she writes books", "她写书"),
    ("she watches football", "她看足球赛"),
    ("she likes apples", "她喜欢苹果"),
    ("she needs water", "她需要水"),
    ("she buys books", "她买书"),
    ("she cleans toys", "她清理玩具"),
    ("they eat bread", "他们吃面包"),
    ("they drink milk", "他们喝牛奶"),
    ("they play toys", "他们玩玩具"),
    ("they read letters", "他们读信"),
    ("they write books", "他们写书"),
    ("they watch football", "他们看足球赛"),
    ("they like apples", "他们喜欢苹果"),
    ("they need water", "他们需要水"),
    ("they buy books", "他们买书"),
    ("they clean toys", "他们清理玩具"),
    ("I like movies", "我喜欢电影"),
    ("I need water", "我需要水"),
    ("I buy books", "我买书"),
    ("I clean toys", "我清理玩具"),
    ("I play music", "我播放音乐"),
    ("I read letters", "我读信件"),
    ("I write movies", "我写剧本"),
    ("I watch football", "我看足球比赛"),
    ("I eat bread", "我吃面包"),
    ("I drink milk", "我喝牛奶"),
    ("I need windows", "我需要窗户"),
    ("I buy football", "我买足球"),
    ("I clean letters", "我整理信件"),
    ("I like bread", "我喜欢面包"),
    ("I need books", "我需要书本"),
    ("I watch toys", "我看玩具"),
    ("I buy movies", "我买电影"),
    ("I clean apples", "我洗苹果"),
    ("I read music", "我读乐谱"),
    ("I write letters", "我写书信"),
    ("you like music", "你喜欢音乐"),
    ("you need toys", "你需要玩具"),
    ("you buy apples", "你买苹果"),
    ("you clean windows", "你擦窗户"),
    ("you play football", "你踢足球"),
    ("you read books", "你看书"),
    ("you write music", "你写乐谱"),
    ("you watch movies", "你看电影"),
    ("you eat apples", "你吃苹果"),
    ("you drink water", "你喝水"),
    ("you need football", "你需要足球"),
    ("you buy bread", "你买面包"),
    ("you clean books", "你整理书本"),
    ("you like windows", "你喜欢窗户"),
    ("you need letters", "你需要信件"),
    ("you watch music", "你听音乐"),
    ("you buy toys", "你买玩具"),
    ("you clean bread", "你整理面包"),
    ("you read movies", "你读剧本"),
    ("you write books", "你写书"),
    ("he likes music", "他喜欢音乐"),
    ("he needs windows", "他需要窗户"),
    ("he buys toys", "他买玩具"),
    ("he cleans apples", "他洗苹果"),
    ("he plays music", "他播放音乐"),
    ("he reads letters", "他读信件"),
    ("he writes books", "他写书"),
    ("he watches football", "他看足球比赛"),
    ("he eats bread", "他吃面包"),
    ("he drinks water", "他喝水"),
    ("he needs books", "他需要书本"),
    ("he buys football", "他买足球"),
    ("he cleans letters", "他整理信件"),
    ("he likes windows", "他喜欢窗户"),
    ("he needs movies", "他需要电影"),
    ("he watches toys", "他看玩具"),
    ("he buys music", "他买音乐"),
    ("he cleans bread", "他整理面包"),
    ("he reads music", "他读乐谱"),
    ("he writes movies", "他写剧本"),
    ("she likes windows", "她喜欢窗户"),
    ("she needs books", "她需要书本"),
    ("she buys movies", "她买电影"),
    ("she cleans toys", "她清理玩具"),
    ("she plays football", "她踢足球"),
    ("she reads books", "她看书"),
    ("she writes letters", "她写书信"),
    ("she watches music", "她听音乐"),
    ("she eats apples", "她吃苹果"),
    ("she drinks milk", "她喝牛奶"),
    ("she needs toys", "她需要玩具"),
    ("she buys bread", "她买面包"),
    ("she cleans windows", "她擦窗户"),
    ("she likes football", "她喜欢足球"),
    ("she needs music", "她需要音乐"),
    ("she watches movies", "她看电影"),
    ("she buys apples", "她买苹果"),
    ("she cleans books", "她整理书本"),
    ("she reads movies", "她读剧本"),
    ("she writes music", "她写乐谱"),
    ("they like windows", "他们喜欢窗户"),
    ("they need books", "他们需要书本"),
    ("they buy music", "他们买音乐"),
    ("they clean toys", "他们清理玩具"),
    ("they play music", "他们播放音乐"),
    ("they read letters", "他们读信件"),
    ("they write movies", "他们写剧本"),
    ("they watch football", "他们看足球比赛"),
    ("they eat bread", "他们吃面包"),
    ("they drink water", "他们喝水"),
    ("they need toys", "他们需要玩具"),
    ("they buy football", "他们买足球"),
    ("they clean letters", "他们整理信件"),
    ("they like bread", "他们喜欢面包"),
    ("they need windows", "他们需要窗户"),
    ("they watch movies", "他们看电影"),
    ("they buy apples", "他们买苹果"),
    ("they clean apples", "他们洗苹果"),
    ("they read music", "他们读乐谱"),
    ("they write books", "他们写书")
]

demo_data_test = [
    ("I like football", "我喜欢足球"),
    ("I need movies", "我需要电影"),
    ("I buy music", "我买音乐"),
    ("I watch football", "我看足球比赛"),
    ("you like books", "你喜欢书"),
    ("you need letters", "你需要信件"),
    ("you buy windows", "你买窗户"),
    ("you read music", "你读乐谱"),
    ("he likes toys", "他喜欢玩具"),
    ("he needs bread", "他需要面包"),
    ("he buys water", "他买水"),
    ("he writes books", "他写书"),
    ("she likes movies", "她喜欢电影"),
    ("she needs music", "她需要音乐"),
    ("she buys apples", "她买苹果"),
    ("she drinks water", "她喝水"),
    ("they like windows", "他们喜欢窗户"),
    ("they need toys", "他们需要玩具"),
    ("they buy bread", "他们买面包"),
    ("they clean letters", "他们清理信件")
]

TRAIN_SIZE = len(demo_data_train)
TEST_SIZE = len(demo_data_test)

